name: flutter_application_1
description: Horoscore

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  shared_preferences: ^2.2.2 
  carousel_slider: any
  flutter:
    sdk: flutter
  pedantic: ^1.11.0
  
  flutter_localizations:
    sdk: flutter

  intl: any
  dio: ^5.4.0  # Проверь актуальную версию на pub.dev
  flutter_svg: ^2.0.0+1  # Убедитесь, что используете последнюю версию
  easy_localization: ^3.0.0
  syncfusion_flutter_charts: ^28.2.5+1

dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_localizations:
      enabled: true

flutter:
  uses-material-design: true

  generate: true # Add this line
  
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
   # - assets/l10n/

     
    - assets/images/zodiac/
    - assets/images/zodiac/leo.png
    - assets/images/zodiac/capricorn.png
    - assets/images/zodiac/gemini.png
    - assets/images/zodiac/cancer.png
    - assets/images/zodiac/aries.png
    - assets/images/zodiac/aquarius.png
    - assets/images/icons/
    - assets/langs/
    - assets/icons/