name: flutter_application_1
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  shared_preferences: ^2.2.2 
  flutter:
    sdk: flutter
  pedantic: ^1.11.0
  
  intl: any
  dio: ^5.4.0  # Проверь актуальную версию на pub.dev
  flutter_svg: ^2.0.0+1  # Убедитесь, что используете последнюю версию
  easy_localization: ^3.0.0

dev_dependencies: 
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  generate: true # Add this line
  
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/zodiac/
    - assets/images/zodiac/leo.png
    - assets/images/zodiac/capricorn.png
    - assets/images/zodiac/gemini.png
    - assets/images/zodiac/cancer.png
    - assets/images/zodiac/aries.png
    - assets/images/zodiac/aquarius.png
    - assets/langs/